name: Track Stars

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Track:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      -
        name: Track
        uses: fbuireu/github-star-tracker@v1
        with:
          top-repos: 500
          data-branch: data
          visibility: public
          include-forks: true
          include-charts: true
          smart-sampling: true
          smart-sampling-pages: 50
          chart-line-width: 2
          chart-line-color: #6b63ff
          only-orgs: dockur,qemus,dobtc,vdsm,action-pack
          github-token: ${{ secrets.STAR_TRACKER_TOKEN }}
