name: Track Stars

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Track:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      -
        name: Track
        id: tracker
        uses: fbuireu/github-star-tracker@v1
        with:
          top-repos: 500
          data-branch: data
          visibility: public
          include-forks: true
          include-charts: true
          smart-sampling: true
          smart-sampling-pages: 30
          chart-max-points: 0
          chart-line-width: 2.5
          chart-line-color: 6b63ff
          chart-y-axis-side: right
          chart-smoothing: false 
          only-orgs: dockur,qemus,dobtc,vdsm,action-pack
          github-token: ${{ secrets.STAR_TRACKER_TOKEN }}
      -
        name: Send report
        #if: steps.tracker.outputs.new-stars >= 10 || steps.tracker.outputs.lost-stars >= 5
        uses: action-pack/send-mail@v1
        env:
          NODE_OPTIONS: --dns-result-order=ipv4first
        with:
          to: ${{secrets.MAILTO}}
          from: Github Star Tracker <${{secrets.MAILTO}}>
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: '⭐ Stars changed: ${{ steps.tracker.outputs.total-stars }} total'
          html_body: file://${{ steps.tracker.outputs.report-html-path }}
